# Generated by Django 2.2.7 on 2019-11-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191119_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='itemstamp',
            new_name='timestamp',
        ),
    ]
