# Generated by Django 2.2 on 2019-12-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
