# Generated by Django 2.2 on 2019-12-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191221_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='photo',
        ),
    ]
