# Generated by Django 2.2.7 on 2019-11-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
