# Generated by Django 2.2 on 2019-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image1',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
