# Generated by Django 2.2 on 2019-12-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191220_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image1',
        ),
    ]
